# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: tothang96
service: affiliate-serverless
frameworkVersion: '4'
useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-central-1
  environment:
    NODE_ENV: ${env:NODE_ENV}
    ACCESS_KEY_ID: ${env:ACCESS_KEY_ID}
    SECRET_ACCESS_KEY: ${env:SECRET_ACCESS_KEY}
    REGION: ${env:REGION}
    YOUTUBE_API_KEY: ${env:YOUTUBE_API_KEY}
    YOUTUBE_SEARCH_URL: ${env:YOUTUBE_SEARCH_URL}
    YOUTUBE_VIDEO_DETAILS_URL: ${env:YOUTUBE_VIDEO_DETAILS_URL}
    TIKTOK_API_HOST: ${env:TIKTOK_API_HOST}
    TIKTOK_API_KEY: ${env:TIKTOK_API_KEY}
    TIKTOK_SEARCH_URL: ${env:TIKTOK_SEARCH_URL}

functions:
  api:
    handler: dist/index.handler
    timeout: 30
    events:
      - http:
          path: /query/search
          method: POST
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
            maxAge: 86400

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

package:
  exclude:
    - node_modules/**
